# Generated by Django 5.2.6 on 2025-10-26 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_app', '0009_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='disease',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='symptoms',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
