# Generated by Django 5.2.6 on 2025-10-26 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_app', '0011_patient_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='user',
        ),
    ]
