# Generated by Django 5.2.6 on 2025-10-26 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_app', '0013_appointment_appointment_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='appointment_date',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='appointment_time',
        ),
    ]
