# Generated by Django 5.2.6 on 2025-10-26 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_app', '0015_appointment_appointment_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='appointment_date',
        ),
    ]
