# Generated by Django 5.2.6 on 2025-10-28 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_app', '0032_alter_doctor_phone_alter_patient_phone_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='date_joined',
        ),
        migrations.AddField(
            model_name='doctor',
            name='experience',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='qualification',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
