# Generated by Django 5.2.6 on 2025-10-28 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_app', '0033_remove_doctor_date_joined_doctor_experience_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='experience',
            field=models.CharField(blank=True, null=True),
        ),
    ]
